services:
  - type: web
    name: csv2postgres
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 3000
      - key: OPENAI_API_KEY
        sync: false  # This means it will be set manually in Render dashboard 
